services:
  - type: web
    name: curs-cs2
    runtime: node
    plan: free
    buildCommand: npm install --no-audit --no-fund && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        value: '1547252610044665889'
      - key: DISCORD_INVITE_URL
        value: 'https://discord.gg/5QwH43Wd9'
